export const Tasks = [
    {
      id: 1,
      completed: false,
      phase: "Notification",
      team: "Pavan Sood",
      task: "Pavan to share details about the application list",
      status: "not-started",
    },
    {
      id: 2,
      completed: false,
      phase: "Pre-Planning",
      team: "Application team/Pavan Sood",
      task: "Validate and confirm the AWS migration schedule date",
      status: "not-started",
    },
    {
      id: 3,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task:
        "Engage with the application owner for:\n" +
        " 1. Server Scope\n" +
        "2. Required Infra Teams\n" +
        "3. SAT date confirmation",
      status: "not-started",
    },
    {
      id: 4,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Create/update DR plan (REP)",
      status: "not-started",
    },
    {
      id: 5,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Create RITMs",
      status: "not-started",
    },
    {
      id: 6,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Schedule weekly planning calls",
      status: "not-started",
    },
    {
      id: 7,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Engage support teams",
      status: "not-started",
    },
    {
      id: 8,
      completed: false,
      phase: "Pre-Planning",
      team: "Application/HCL Infra/HCL RM Infra Support",
      task: "Update DR plan (REP) in the planning calls",
      status: "not-started",
    },
    {
      id: 9,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Create Change Control",
      status: "not-started",
    },
    {
      id: 10,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "schedule ",
      status: "not-started",
    },
    {
      id: 11,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "CTASK Acknowledgement",
      status: "not-started",
    },
    {
      id: 12,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Joining DRC weekly call on Tuesday to give status update",
      status: "not-started",
    },
    {
      id: 13,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Create and share .csv files required for DNS flips",
      status: "not-started",
    },
    {
      id: 14,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Attending CAB (Change Advisory Board) meetings",
      status: "not-started",
    },
    {
      id: 15,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Scheduling SAT Execution calls",
      status: "not-started",
    },
    {
      id: 16,
      completed: false,
      phase: "Pre-Planning",
      team: "HCL RM Infra Support",
      task: "Confirm Prerequisites completion",
      status: "not-started",
    },
    {
      id: 17,
      completed: false,
      phase: "Pre-Planning",
      team: "Application Team (Optional compliance test)",
      task: "Engage business testers",
      status: "not-started",
    },
    {
      id: 18,
      completed: false,
      phase: "Execution",
      team: "HCL RM Infra Support",
      task: "Provide status updates on MIP dashboard",
      status: "not-started",
    },
    {
      id: 19,
      completed: false,
      phase: "Execution",
      team: "HCL RM Infra Support",
      task: "Drive the SAT as per REP document",
      status: "not-started",
    },
    {
      id: 20,
      completed: false,
      phase: "Execution",
      team: "HCL RM Infra Support",
      task: "Collect Evidences/Artifacts",
      status: "not-started",
    },
    {
      id: 21,
      completed: false,
      phase: "Execution",
      team: "HCL RM Infra Support",
      task: "Closure of Change Request",
      status: "not-started",
    },
    {
      id: 22,
      completed: false,
      phase: "Execution",
      team: "HCL RM Infra Support",
      task: "Document issues and learnings",
      status: "not-started",
    },
    {
      id: 23,
      completed: false,
      phase: "Execution",
      team: "HCL RM Infra Support",
      task: "Contact Pavan Sood when issues arises",
      status: "not-started",
    },
    {
      id: 24,
      completed: false,
      phase: "Post-Execution",
      team: "HCL RM Infra Support",
      task: "Create SAT Report",
      status: "not-started",
    },
    {
      id: 25,
      completed: false,
      phase: "Post-Execution",
      team: "HCL RM Infra Support",
      task: "Send Closure Email",
      status: "not-started",
    },
    {
      id: 26,
      completed: false,
      phase: "Post-Execution",
      team: "HCL RM Infra Support",
      task: "Updating all SAT docs in SAT sharepoint",
      status: "not-started",
    },
    {
      id: 27,
      completed: false,
      phase: "Post-Execution",
      team: "HCL RM Infra Support",
      task: "Updating SAT Report in BOX folder",
      status: "not-started",
    },
    {
      id: 28,
      completed: false,
      phase: "Post-Execution",
      team: "Application/RM team (Optional compliance test)",
      task: "Track and Report RTA",
      status: "not-started",
    },
    {
      id: 29,
      completed: false,
      phase: "Post-Execution",
      team: "Application/RM team (Optional compliance test)",
      task: "Determine Succes Rating - Evaluate SAT test outcomes",
      status: "not-started",
    },
    {
      id: 30,
      completed: false,
      phase: "Post-Execution",
      team: "Application/RM team (Optional compliance test)",
      task: "Collect Evidence/Artifacts",
      status: "not-started",
    },
    {
      id: 31,
      completed: false,
      phase: "Post-Execution",
      team: "Application/RM team (Optional compliance test)",
      task: "Collect and share test results - Gather and share results/SAT report with ETS DR team",
      status: "not-started",
    },
    {
      id: 32,
      completed: false,
      phase: "Post-Execution",
      team: "Application/HCL RM Infra Support",
      task: "Updating all SAT docs in SAT sharepoint",
      status: "not-started",
    },
  ];
  