export const Tasks = [
  {
    id: 1,
    completed: false,
    phase: "Notification",
    team: "Pavan Sood",
    task: "Pavan to share details about the application list",
  },
  {
    id: 2,
    completed: false,
    phase: "Pre-Planning",
    team: "Application team/Pavan Sood",
    task: "Validate and confirm the AWS migration schedule date",
  },
  {
    id: 3,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Engage with the application owner for:\n 1. Server Scope\n2. Required Infra Teams\n3. SAT date confirmation",
  },
  {
    id: 4,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Create/update DR plan (REP)",
  },
  {
    id: 5,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Create RITMs",
  },
  {
    id: 6,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Schedule weekly planning calls",
  },
  {
    id: 7,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Engage support teams",
  },
  {
    id: 8,
    completed: false,
    phase: "Pre-Planning",
    team: "Application/HCL Infra/HCL RM Infra Support",
    task: "Update DR plan (REP) in the planning calls",
  },
  {
    id: 9,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Create Change Control",
  },
  {
    id: 10,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "schedule ",
  },
  {
    id: 11,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "CTASK Acknowledgement",
  },
  {
    id: 12,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Joining DRC weekly call on Tuesday to give status update",
  },
  {
    id: 13,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Create and share .csv files required for DNS flips",
  },
  {
    id: 14,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Attending CAB (Change Advisory Board) meetings",
  },
  {
    id: 15,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Scheduling SAT Execution calls",
  },
  {
    id: 16,
    completed: false,
    phase: "Pre-Planning",
    team: "HCL RM Infra Support",
    task: "Confirm Prerequisites completion",
  },
  {
    id: 17,
    completed: false,
    phase: "Pre-Planning",
    team: "Application Team (Optional compliance test)",
    task: "Engage business testers",
  },
  {
    id: 18,
    completed: false,
    phase: "Execution",
    team: "HCL RM Infra Support",
    task: "Provide status updates on MIP dashboard",
  },
  {
    id: 19,
    completed: false,
    phase: "Execution",
    team: "HCL RM Infra Support",
    task: "Drive the SAT as per REP document",
  },
  {
    id: 20,
    completed: false,
    phase: "Execution",
    team: "HCL RM Infra Support",
    task: "Collect Evidences/Artifacts",
  },
  {
    id: 21,
    completed: false,
    phase: "Execution",
    team: "HCL RM Infra Support",
    task: "Closure of Change Request",
  },
  {
    id: 22,
    completed: false,
    phase: "Execution",
    team: "HCL RM Infra Support",
    task: "Document issues and learnings",
  },
  {
    id: 23,
    completed: false,
    phase: "Execution",
    team: "HCL RM Infra Support",
    task: "Contact Pavan Sood when issues arises",
  },
  {
    id: 24,
    completed: false,
    phase: "Post-Execution",
    team: "HCL RM Infra Support",
    task: "Create SAT Report",
  },
  {
    id: 25,
    completed: false,
    phase: "Post-Execution",
    team: "HCL RM Infra Support",
    task: "Send Closure Email",
  },
  {
    id: 26,
    completed: false,
    phase: "Post-Execution",
    team: "HCL RM Infra Support",
    task: "Updating all SAT docs in SAT sharepoint",
  },
  {
    id: 27,
    completed: false,
    phase: "Post-Execution",
    team: "HCL RM Infra Support",
    task: "Updating SAT Report in BOX folder",
  },
  {
    id: 28,
    completed: false,
    phase: "Post-Execution",
    team: "Application/RM team (Optional compliance test)",
    task: "Track and Report RTA",
  },
  {
    id: 29,
    completed: false,
    phase: "Post-Execution",
    team: "Application/RM team (Optional compliance test)",
    task: "Determine Succes Rating - Evaluate SAT test outcomes",
  },
  {
    id: 30,
    completed: false,
    phase: "Post-Execution",
    team: "Application/RM team (Optional compliance test)",
    task: "Collect Evidence/Artifacts",
  },
  {
    id: 31,
    completed: false,
    phase: "Post-Execution",
    team: "Application/RM team (Optional compliance test)",
    task: "Collect and share test results - Gather and share results/SAT report with ETS DR team",
  },
  {
    id: 32,
    completed: false,
    phase: "Post-Execution",
    team: "Application/HCL RM Infra Support",
    task: "Updating all SAT docs in SAT sharepoint",
  },

];
